### ISSUE TITLE
"Sign In" instead of "Sign Up" in Home Page

### ISSUE THREAD

**Issue by V1shvesh** [V1shvesh/SoundPlay#1]
Comment below if you didn't figure this out...

**Comment by V1shvesh** [comment]
Just have to change the text on the sign up button

**Comment by darkHarry** [comment]
`sign up` feels right.

**Comment by V1shvesh** [comment]
let abhinav fix this, he'll get some experience

**Comment by oKaMi04** [comment]
ok guys here i m

**Comment by darkHarry** [comment]
@bhediya thanks for the input but you have just changed the button text in `player.html` file please do so kindly in `index.html` too.
